#!/bin/sh

F=$1

echo source build variables from script: $F at dir `pwd`

. ./$F

runsed() {
    $SED 's/\\/\\\\/g'
}

echo "--------foobar stdout --------"
echo "--------foobar stderr --------" > /dev/stderr

echo "BUILD_DATE: $BUILD_DATE"
echo BUILDSTAMP="'`date -u +'%Y-%m-%d %T' -d @$BUILD_DATE`'"
echo ____cyg: $CYGPATH_W ____ $pkgdatadir

echo '/* generated by Makefile */' > libpath.tmp
echo '#define SCM_PKGDATA_DIR "'`$CYGPATH_W $pkgdatadir | runsed`'"' >> libpath.tmp
echo '#define SCM_LIBRARY_DIR "'`$CYGPATH_W $pkgdatadir/$GUILE_EFFECTIVE_VERSION | runsed`'"'>>libpath.tmp
echo '#define SCM_SITE_DIR "'`$CYGPATH_W $sitedir | runsed`'"' >> libpath.tmp
echo '#define SCM_GLOBAL_SITE_DIR "'`$CYGPATH_W $pkgdatadir/site | runsed`'"' >> libpath.tmp
echo '#define SCM_LIB_DIR "'`$CYGPATH_W $libdir | runsed`'"' >> libpath.tmp
echo '#define SCM_EXTENSIONS_DIR "'`$CYGPATH_W $pkglibdir/$GUILE_EFFECTIVE_VERSION/extensions | runsed`'"' >> libpath.tmp
echo '#define SCM_CCACHE_DIR "'`$CYGPATH_W $pkglibdir/$GUILE_EFFECTIVE_VERSION/ccache | runsed`'"' >> libpath.tmp
echo '#define SCM_SITE_CCACHE_DIR "'`$CYGPATH_W $pkglibdir/$GUILE_EFFECTIVE_VERSION/site-ccache | runsed`'"' >> libpath.tmp
echo '#define SCM_EFFECTIVE_VERSION "'`$CYGPATH_W $GUILE_EFFECTIVE_VERSION | runsed`'"' >> libpath.tmp
echo '#define SCM_BUILD_INFO { \' >> libpath.tmp
echo '	{ "srcdir",        "'`cd $srcdir; pwd | xargs $CYGPATH_W | runsed`'" }, \' >> libpath.tmp
echo ' { "top_srcdir",    "'`$CYGPATH_W $top_srcdir_absolute | runsed`'" }, \' >> libpath.tmp
echo '	{ "prefix",	   "'`$CYGPATH_W $prefix | runsed`'" }, \' >> libpath.tmp
echo '	{ "exec_prefix",   "'`$CYGPATH_W $exec_prefix | runsed`'" }, \' >> libpath.tmp
echo '	{ "bindir",	   "'`$CYGPATH_W $bindir | runsed`'" }, \' >> libpath.tmp
echo '	{ "sbindir",	   "'`$CYGPATH_W $sbindir | runsed`'" }, \' >> libpath.tmp
echo '	{ "libexecdir",	   "'`$CYGPATH_W $libexecdir | runsed`'" }, \' >> libpath.tmp
echo '	{ "datadir",	   "'`$CYGPATH_W $datadir | runsed`'" }, \' >> libpath.tmp
echo '	{ "sysconfdir",	   "'`$CYGPATH_W $sysconfdir | runsed`'" }, \' >> libpath.tmp
echo '	{ "sharedstatedir", "'`$CYGPATH_W @sharedstatedir | runsed`'" }, \' >> libpath.tmp
echo '	{ "localstatedir", "'`$CYGPATH_W $localstatedir | runsed`'" }, \' >> libpath.tmp
echo '	{ "libdir",	   "'`$CYGPATH_W $libdir | runsed`'" }, \' >> libpath.tmp
echo '	{ "ccachedir",	   SCM_CCACHE_DIR }, \' >> libpath.tmp
echo '	{ "infodir",	   "'`$CYGPATH_W $infodir | runsed`'" }, \' >> libpath.tmp
echo '	{ "mandir",	   "'`$CYGPATH_W $mandir | runsed`'" }, \' >> libpath.tmp
echo '	{ "includedir",	   "'`$CYGPATH_W $includedir | runsed`'" }, \' >> libpath.tmp
echo '	{ "pkgdatadir",	   "'`$CYGPATH_W $pkgdatadir  | runsed`'" }, \' >> libpath.tmp
echo '	{ "pkglibdir",	   "'`$CYGPATH_W $pkglibdir  | runsed`'" }, \' >> libpath.tmp
echo '	{ "pkgincludedir", "'`$CYGPATH_W $pkgincludedir  | runsed`'" }, \' >> libpath.tmp
echo '	{ "extensiondir", "'`$CYGPATH_W $pkglibdir/$GUILE_EFFECTIVE_VERSION/extensions | runsed`'" }, \' >> libpath.tmp
echo '	{ "guileversion", "$GUILE_VERSION" }, \' >> libpath.tmp
echo '	{ "libguileinterface", "$LIBGUILE_INTERFACE" }, \' >> libpath.tmp
echo '	{ "LIBS",	   "$GUILE_LIBS" }, \' >> libpath.tmp
echo '	{ "CFLAGS",	   "$GUILE_CFLAGS" }, \' >> libpath.tmp
echo '	{ "buildstamp",    "'`date -u +'%Y-%m-%d %T' -d @$BUILD_DATE`'" }, \' >> libpath.tmp
echo '}' >> libpath.tmp

